// cy.get('[data-test=""]')

describe('navigation on small screens', () => {
  beforeEach(()=>{
    cy.viewport("iphone-xr")
  })
  it('toggles and is dynamic on home', () => {
    cy.visit('/')
    cy.get('[data-test="cart"]')
    cy.get('[data-test="hamburger"]').click()
    cy.get('[data-test="nav-mobile"]').contains('Close').should('be.visible')
    cy.get('[data-test="nav-mobile"]').contains('Home').should('not.be.visible')
    cy.get('[data-test="nav-mobile"]').contains('Keyboards').should('be.visible')
    cy.get('[data-test="nav-mobile"]').contains('Keycaps').should('be.visible')
    cy.get('[data-test="nav-mobile"]').contains('Deskmats').should('be.visible')
    cy.get('[data-test="close-hamburger"]').click()
    cy.get('[data-test="nav-mobile"]').should('not.exist')
  })

  it('toggles and is dynamic on keyboards', () => {
    cy.visit('/keyboards')
    cy.get('[data-test="cart"]')
    cy.get('[data-test="hamburger"]').click()
    cy.get('[data-test="nav-mobile"]').contains('Close').should('be.visible')
    cy.get('[data-test="nav-mobile"]').contains('Home').should('be.visible')
    cy.get('[data-test="nav-mobile"]').contains('Keyboards').should('not.be.visible')
    cy.get('[data-test="nav-mobile"]').contains('Keycaps').should('be.visible')
    cy.get('[data-test="nav-mobile"]').contains('Deskmats').should('be.visible')
    cy.get('[data-test="close-hamburger"]').click()
    cy.get('[data-test="nav-mobile"]').should('not.exist')
  })

  it('toggles and is dynamic on keycaps', () => {
    cy.visit('/keycaps')
    cy.get('[data-test="cart"]')
    cy.get('[data-test="hamburger"]').click()
    cy.get('[data-test="nav-mobile"]').contains('Close').should('be.visible')
    cy.get('[data-test="nav-mobile"]').contains('Home').should('be.visible')
    cy.get('[data-test="nav-mobile"]').contains('Keyboards').should('be.visible')
    cy.get('[data-test="nav-mobile"]').contains('Keycaps').should('not.be.visible')
    cy.get('[data-test="nav-mobile"]').contains('Deskmats').should('be.visible')
    cy.get('[data-test="close-hamburger"]').click()
    cy.get('[data-test="nav-mobile"]').should('not.exist')
  })

  it('toggles and is dynamic on deskmats', () => {
    cy.visit('/deskmats')
    cy.get('[data-test="cart"]')
    cy.get('[data-test="hamburger"]').click()
    cy.get('[data-test="nav-mobile"]').contains('Close').should('be.visible')
    cy.get('[data-test="nav-mobile"]').contains('Home').should('be.visible')
    cy.get('[data-test="nav-mobile"]').contains('Keyboards').should('be.visible')
    cy.get('[data-test="nav-mobile"]').contains('Keycaps').should('be.visible')
    cy.get('[data-test="nav-mobile"]').contains('Deskmats').should('not.be.visible')
    cy.get('[data-test="close-hamburger"]').click()
    cy.get('[data-test="nav-mobile"]').should('not.exist')
  })

  it('toggles and is non dynamic on checkout', () => {
    cy.visit('/checkout')
    cy.get('[data-test="cart"]')
    cy.get('[data-test="hamburger"]').click()
    cy.get('[data-test="nav-mobile"]').contains('Close').should('be.visible')
    cy.get('[data-test="nav-mobile"]').contains('Home').should('be.visible')
    cy.get('[data-test="nav-mobile"]').contains('Keyboards').should('be.visible')
    cy.get('[data-test="nav-mobile"]').contains('Keycaps').should('be.visible')
    cy.get('[data-test="nav-mobile"]').contains('Deskmats').should('be.visible')
    cy.get('[data-test="close-hamburger"]').click()
    cy.get('[data-test="nav-mobile"]').should('not.exist')
  })
})